spring.application.name=bibliotecaria_devops

logging.file.path=logs/
logging.file.name=logs/application.log
logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.com.ecernare=DEBUG

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true

#datasource settings
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotecaria_db?currentSchema=public
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin123

#data settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#console settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.h2.console.settings.trace=false
#spring.jpa.show-sql=true

server.error.include-message=always
